server:
  # 服务端口
  port: 9003

eureka:
  client:
    service-url:
      # 服务注册中心地址
      defaultZone: http://localhost:8888/eureka/

feign:
  client:
    config:
      # 默认为所有的feign client做配置(注意和上例github-client是同级的)
      default:
        # 连接超时时间
        connectTimeout: 5000
        readTimeout: 5000

spring:
  application:
    # 服务名称
    name: customer-service