server:
  # 服务端口
  port: 9004

eureka:
  client:
    service-url:
      # 服务注册中心地址
      defaultZone: http://localhost:8888/eureka/

spring:
  application:
    # 服务名称
    name: oauth2-service
  redis:
    host: 127.0.0.1
    database: 10
    port: 7002
    password: 123456

